# Generated by Django 4.1.2 on 2022-12-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="price",
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
